### ISSUE TITLE
개인런 기능 개발

### ISSUE THREAD

**Issue by sjsjsj1246** [MoyeoRun/MoyeoRun_Front#14]
## 구현사항
- 사용자의 위치를 2초마다 전송함 HTTP POST
  - UseInterval 
  - 오차를 줄이기 위한 방법 적용
    - 0.5초마다 데이터를 수집해 평균값을 전달
- 서버에서 러닝 데이터를 가져와 랜더링
  - 위치 배열을 이용해 지도에 poly line으로 랜더링해주기
  - 총 이동 거리, 평균 페이스, 시간
- 러닝 시간 증가 로직
- 러닝 일시정지 기능
- 음성 피드백

## 고려사항
- 네트워크 장애로 중간에 러닝 데이터 전송에 실패했을 때 처리 해줄 것
  - onFailure -> 버퍼에 배열 형태로 전송하지 못한 러닝 데이터를 쌓아놓고 한번에 보냄 
  - @InHyeok-J 

## 참고자료
- GPS 위치 정확도 올리기
  - 라이브러리 자체 해결 : [블로그](https://velog.io/@go_by/react-native-location-%EB%B3%B4%EB%8B%A4-%EB%8D%94-%EC%A0%95%ED%99%95%ED%95%9C-%EC%9C%84%EC%B9%98-%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0)
  - 수학적 해결 : low pass filter / Kalman filter
- react-native-tts(음성 피드백용 TTS) : https://dev-yakuza.posstree.com/ko/react-native/react-native-tts/

**Comment by InHyeok-J** [comment]
버퍼에 배열로 저장한다는 건, 네트워크 장애로 실패시, 버퍼에 2초마다 평균계산된 데이터가 쌓인다는건가?, 이후 다음 2초가 지날때 한번에 보내고??

**Comment by InHyeok-J** [comment]
@sjsjsj1246

**Comment by sjsjsj1246** [comment]
@InHyeok-J 바로 그겁니다
