### ISSUE TITLE
MapView 작동되지 않는 이슈

### ISSUE THREAD

**Issue by Sangjun-man** [MoyeoRun/MoyeoRun_Front#17]
### MapView가 작동하지 않음..

> expo.dev 공식문서에 있는대로 시도해보았으나 작동하지 않음ㅠㅠㅠ

## 시도해본 내용

- 구글 Map SDK API 등록 및 app.json 수정
![image](https://user-images.githubusercontent.com/66112027/135388334-c5cafcb4-045c-4ac0-97fa-3fa166c48be4.png)
![image](https://user-images.githubusercontent.com/66112027/135388399-f4eaecd9-28f4-44e5-b57f-c0eb2d2230a8.png)
이방법은 expo로 테스트할 때 말고 실제 빌드할 때 설정해주어야 하는것이라고함, 나중에 해야하는 부분

## 확인해볼 내용
![image](https://user-images.githubusercontent.com/66112027/135387518-e8ac5bd3-76d7-4cc8-8369-237f836e7432.png)
출처 : [react-native-map 깃헙 레포](https://github.com/react-native-maps/react-native-maps)
보니까 react-native 최신버전에서만 이 모듈을 지원한다고 하는데
현재 rn 버전 : 0.63, react-native-map : 0.28
최신 rn 버젼 : 0.65, react-native-map : 0.29

버전호환의 문제인가?? 싶다. 한번 확인해보려고함

**Comment by Sangjun-man** [comment]
### rn 버전과 상관없었다
expo install react-native-map 하면
expo sdk(42) - rn(0.63) - react-native-maps(0.28) 
호환되는 버전으로 install 해줌

**Comment by sjsjsj1246** [comment]
해결됐나요? 예전에 했을 땐 구글 맵 SDK 등록한적이 없었는데..

**Comment by Sangjun-man** [comment]
### MapView 화면에 띄우기 성공
> MapView 연동문제가 아닌 컨테이너 사이즈 설정의 문제였던것 같음,,,
<img src="https://user-images.githubusercontent.com/66112027/135395284-a9e0c4ef-dda3-4b85-b41f-6a2896e7547b.png" width="30%" height="30%">



## 트러블슈팅
참고 링크 [No map whatsoever 부분 참고했음](https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md)
# 작성코드
![image](https://user-images.githubusercontent.com/66112027/135395816-948b7ab1-dc25-49a2-95c8-21c47e556dfa.png)
 display:flex 속성을 가진 상위 태그 안에 flex={1}으로 여백없이 채우려고 했으나 무슨 문제인지 w=100%까지만 채워지는 현상이 발생하여
style 변수를 만들어서 계산된 px값을 넣어주었읍니다
이 부분은 좀 더 공부할 필요가 있을듯 싶음......

**Comment by Sangjun-man** [comment]
### MapView는 native 컴포넌트의 StyleProp<ViewStyle>를 받는다
mapView에 native 컴포넌트의 스타일을 지정하듯 똑같이 지정해줄수 있다

<img src="https://user-images.githubusercontent.com/66112027/135412815-76ae0130-407a-4288-b9da-16d7fd67d645.png" >


적용화면
<img src="https://user-images.githubusercontent.com/66112027/135412331-763db1ef-a5a0-481c-95ec-3e8e62070aef.png" width="30%" height="30%" >

**Comment by sjsjsj1246** [comment]
고생하셨습니다....
