### ISSUE TITLE
스크린 디렉토리 삭제 제안

### ISSUE THREAD

**Issue by sjsjsj1246** [MoyeoRun/MoyeoRun_Front#23]
리액트 웹 프로젝트에서 react-router를 사용했고 그 라우터와 1:1대응하는 Page라는 컴포넌트와 디렉터리 구조를 가져왔습니다.
현재 프로젝트에서 Screen이 그 역할입니다.
기존에는 서로 다른 기능의 여러 로직들을 합쳐 하나의 Page를 만들었기에 Conainer들을 여러개 나눠 분리를 했습니다만 모바일 프로젝트를 해보니 현재 앱에는 필요없는 구조인 것 같아 Screen디렉터리 구조를 버릴 것을 제안합니다.

@Sangjun-man

**Comment by Sangjun-man** [comment]
네 좋습니다~ 이후에 단체런 스크린에서도 여러 로직들을 모아서 한페이지에 보여주는 경우가 없을거 같습니다 확인이요!!
